name: circlegraph
description: Create graphs with a root node and several child nodes.
version: 0.0.2
homepage: https://github.com/herrytco/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: